---
  - name: Create VPC
    cloudformation:
      stack_name: "{{application}}-{{env}}-vpc"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/public_vpc_and_two_public_subnets.yml"
      stack_policy: "cloudformation/allow_update_policy.json"
      template_parameters:
        VPCCIDR: "{{vpc_cidr}}"
        PublicSubnetOneCIDR: "{{public_subnet_one_cidr}}"
        PublicSubnetTwoCIDR: "{{public_subnet_two_cidr}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        environment: "{{env}}"

  - name: Deploy using fargate
    cloudformation:
      stack_name: "{{application}}-{{env}}-fargate"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/fargate.yml"
      stack_policy: "cloudformation/allow_update_policy.json"
      template_parameters:
        VPCStackName: "{{application}}-{{env}}-vpc"
        ServiceName: "{{application}}-{{deploy_version}}"
        ImageUrl: "{{account_id}}.dkr.ecr.{{aws_region}}.amazonaws.com/{{application}}-{{env}}:{{deploy_version}}"
        ContainerPort: "{{container_port}}"
        ContainerCpu: "{{container_cpu}}"
        ContainerMemory: "{{container_memory}}"
        ALBPath: "{{alb_path}}"
        Priority: "{{priority}}"
        DesiredCount: "{{desired_count}}"
        Role: "{{role}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        environment: "{{env}}"