---
- hosts: deploy
  connection: local
  gather_facts: False
  tasks:
    - name: Launch ec2 instance and create ami
      cloudformation:
        stack_name: "{{application}}-{{env}}-ec2-ami"
        state: present
        region: "{{aws_region}}"
        disable_rollback: true
        template: "cloudformation/ami.yml"
        stack_policy: "cloudformation/allow_update_policy.json"
        tags:
          project: "{{project}}"
          application: "{{application}}"
          environment: "{{env}}"