AWSTemplateFormatVersion: 2010-09-09
Description: >
        This stack builds a VPC with a pair of public spread across two Availability Zones.
        It deploys an Internet Gateway, with a default route on the public subnets.
Parameters:
  VPCCIDR:
    Description: "VPC CIDR"
    Type: String
  PublicSubnetOneCIDR:
    Description: "Subnet One CIDR"
    Type: String
  PublicSubnetTwoCIDR:
    Description: "Subnet Two CIDR"
    Type: String
  VPCName:
    Description: "The name of VPC"
    Type: String
  PublicSubnetOneName:
    Description: "The name of public subnet one"
    Type: String
  PublicSubnetTwoName:
    Description: "The name of public subnet two"
    Type: String
  InternetGatewayName:
    Description: "The name of internet gateway"
    Type: String
  PublicRouteTableName:
    Description: "The name of public route table"
    Type: String
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: !Ref VPCCIDR
      Tags:
        - Key: Name
          Value: !Ref VPCName
  PublicSubnetOne:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: 'AWS::Region'
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetOneCIDR
      Tags:
        - Key: Name
          Value: !Ref PublicSubnetOneName
      MapPublicIpOnLaunch: true
  PublicSubnetTwo:
    Type: 'AWS::EC2::Subnet'
    Properties:
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: 'AWS::Region'
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetTwoCIDR
      Tags:
        - Key: Name
          Value: !Ref PublicSubnetTwoName
      MapPublicIpOnLaunch: true
  InternetGateway:
    Type: 'AWS::EC2::InternetGateway'
    Properties:
      Tags:
        - Key: Name
          Value: !Ref InternetGatewayName
  GatewayAttachement:
    Type: 'AWS::EC2::VPCGatewayAttachment'
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway
  PublicRouteTable:
    Type: 'AWS::EC2::RouteTable'
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Ref PublicRouteTableName
  PublicRoute:
    Type: 'AWS::EC2::Route'
    DependsOn: GatewayAttachement
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway
  PublicSubnetOneRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetOne
      RouteTableId: !Ref PublicRouteTable
  PublicSubnetTwoRouteTableAssociation:
    Type: 'AWS::EC2::SubnetRouteTableAssociation'
    Properties:
      SubnetId: !Ref PublicSubnetTwo
      RouteTableId: !Ref PublicRouteTable
Outputs:
  VPCId:
      Description: The ID of the VPC that this stack is deployed in
      Value: !Ref VPC
      Export:
        Name: !Join
          - ':'
          - - !Ref 'AWS::StackName'
            - VPCId
  PublicSubnetOne:
    Description: Public subnet one
    Value: !Ref PublicSubnetOne
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - PublicSubnetOne
  PublicSubnetTwo:
    Description: Public subnet two
    Value: !Ref PublicSubnetTwo
    Export:
      Name: !Join
        - ':'
        - - !Ref 'AWS::StackName'
          - PublicSubnetTwo