---
  - name: Create VPC
    cloudformation:
      stack_name: "{{application}}-{{env}}-vpc"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/vpc_and_two_public_subnets.yml"
      stack_policy: "cloudformation/allow_update_policy.json"
      template_parameters:
        VPCCIDR: "{{vpc_cidr}}"
        PublicSubnetOneCIDR: "{{public_subnet_one_cidr}}"
        PublicSubnetTwoCIDR: "{{public_subnet_two_cidr}}"
        VPCName: "{{vpc_name}}"
        PublicSubnetOneName: "{{public_subnet_one_name}}"
        PublicSubnetTwoName: "{{public_subnet_two_name}}"
        InternetGatewayName: "{{internet_gateway_name}}"
        PublicRouteTableName: "{{public_route_table_name}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        environment: "{{env}}"
    tags: vpc