---
  - name: Deploy using fargate
    cloudformation:
      stack_name: "{{application}}-{{env}}-fargate"
      state: present
      region: "{{aws_region}}"
      disable_rollback: true
      template: "cloudformation/fargate.yml"
      stack_policy: "cloudformation/allow_update_policy.json"
      template_parameters:
        VPCStackName: "{{application}}-{{env}}-vpc"
        ServiceName: "{{application}}-{{env}}-{{deploy_version}}"
        ImageUrl: "{{account_id}}.dkr.ecr.{{aws_region}}.amazonaws.com/{{application}}-{{env}}:{{deploy_version}}"
        ContainerPort: "{{container_port}}"
        ContainerCpu: "{{container_cpu}}"
        ContainerMemory: "{{container_memory}}"
        DesiredCount: "{{desired_count}}"
        Role: "{{role}}"
        LogGroupStackName: "{{application}}-{{env}}-log-group"
        AWSLogRegion: "{{aws_region}}"
      tags:
        project: "{{project}}"
        application: "{{application}}"
        environment: "{{env}}"
    tags: fargate